01-gethostname: 01-gethostname.c
	gcc 01-gethostname.c -o 01-gethostname

02-getaddrinfo: 02-getaddrinfo.c
	gcc 02-getaddrinfo.c -o 02-getaddrinfo

03-UDPsend: 03-UDPsend.c
	gcc 03-UDPsend.c -o 03-UDPsend

04-UDPrecv: 04-UDPrecv.c
	gcc 04-UDPrecv.c -o 04-UDPrecv

UDPconnection: UDPconnection.c
	gcc UDPconnection.c -o UDPconnection



quickGuide: quickGuide.c
	gcc quickGuide.c -o quickGuide

09-UDPserver: 09-UDPserver.c
	gcc 09-UDPserver.c -o 09-UDPserver

serverTCP: serverTCP.c
	gcc serverTCP.c -o serverTCP
